project:
  type: website
  output-dir: websitedocs

website:
  title: "My Site"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Website"
        contents:
          - index.qmd
          - purpose.qmd
      - section: "Extra Info"
        contents:
          - extrainfo.qmd

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/nmadhuyaminiedu

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual


